"""Constants for Dashboard Entity Checker."""

DOMAIN = "dashboard_entity_checker"
NAME = "Dashboard Entity Checker"
VERSION = "0.1.1"

CONF_DASHBOARD = "dashboard_url_path"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_NOTIFICATIONS = "notifications"

DEFAULT_DASHBOARD = "my-ha-dashboard"
DEFAULT_SCAN_INTERVAL = 5  # minutes
DEFAULT_NOTIFICATIONS = True

# Entity domains to scan for in dashboard configs
ENTITY_DOMAINS = [
    "alarm_control_panel", "automation", "binary_sensor", "button", "calendar",
    "camera", "climate", "cover", "device_tracker", "fan", "group", "humidifier",
    "input_boolean", "input_button", "input_datetime", "input_number",
    "input_select", "input_text", "light", "lock", "media_player", "number",
    "person", "remote", "scene", "script", "select", "sensor", "switch",
    "timer", "update", "vacuum", "weather", "zone",
]

# Service-like strings that look like entity IDs but aren't
PSEUDO_ENTITIES = {
    "button.press",
    "climate.set_temperature",
    "climate.set_hvac_mode",
    "media_player.media_play_pause",
    "media_player.media_stop",
    "media_player.volume_up",
    "media_player.volume_down",
    "media_player.volume_set",
    "media_player.play_media",
    "input_number.increment",
    "input_number.decrement",
    "alarm_control_panel.alarm_arm_away",
    "alarm_control_panel.alarm_arm_home",
    "alarm_control_panel.alarm_disarm",
    "alarm_control_panel.alarm_arm_night",
    "alarm_control_panel.alarm_arm_vacation",
    "alarm_control_panel.alarm_trigger",
    "cover.open_cover",
    "cover.close_cover",
    "cover.stop_cover",
    "cover.toggle",
    "light.toggle",
    "light.turn_on",
    "light.turn_off",
    "switch.toggle",
    "switch.turn_on",
    "switch.turn_off",
    "fan.toggle",
    "fan.turn_on",
    "fan.turn_off",
    "script.turn_on",
    "script.turn_off",
    "script.toggle",
    "automation.turn_on",
    "automation.turn_off",
    "automation.toggle",
    "automation.trigger",
    "scene.apply",
    "scene.create",
    "scene.turn_on",
    "scene.turn_off",
    "vacuum.start",
    "vacuum.stop",
    "vacuum.return_to_base",
    "vacuum.start_pause",
    "humidifier.toggle",
    "humidifier.turn_on",
    "humidifier.turn_off",
    "lock.lock",
    "lock.unlock",
    "media_player.turn_on",
    "media_player.turn_off",
    "media_player.media_next",
    "media_player.media_previous",
    "media_player.media_play",
    "media_player.select_source",
    "media_player.select_sound_mode",
    "update.install",
    "homeassistant.turn_on",
    "homeassistant.turn_off",
    "homeassistant.toggle",
    "homeassistant.restart",
    "homeassistant.stop",
    "homeassistant.check_config",
    "homeassistant.reload_all",
    "homeassistant.reload_core_config",
    "input_boolean.toggle",
    "input_boolean.turn_on",
    "input_boolean.turn_off",
    "input_select.select_option",
    "input_select.select_next",
    "input_select.select_previous",
    "input_datetime.set_datetime",
    "input_number.set_value",
    "input_text.set_value",
    "number.set_value",
    "select.select_option",
    "select.select_first",
    "select.select_last",
    "select.select_next",
    "select.select_previous",
    "timer.start",
    "timer.pause",
    "timer.cancel",
    "timer.change",
    "timer.finish",
    "notify.send_message",
    "input_button.press",
    "script.turn_light_to_random_color",
    "weather.last_updated",
    "sensor.time",
    "sensor.date_time",
    "sun.sun",
}
